# Generated by Django 3.0 on 2022-09-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'INSERT INTO profiles_profile SELECT * FROM oc_lettings_site_profile;'
        )
    ]
