# Generated by Django 3.0 on 2022-09-15 19:31

from django.db import migrations


class Migration(migrations.Migration):
    """Custom Migration to populate the new tables (letting, address) with the current data."""

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'INSERT INTO lettings_address SELECT * FROM oc_lettings_site_address;'
        ),
        migrations.RunSQL(
            'INSERT INTO lettings_letting SELECT * FROM oc_lettings_site_letting;'
        )
    ]
